name: Update Year in license

on: workflow_dispatch

jobs:
  update-license-year:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: FantasticFiasco/action-update-license-year@v2
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          path: src/**/*.js
          transform: (?<=Maktoom Ahmed )(?<from>\d{4})?-?(\d{4})?
